import { useState } from 'react'
import { MockAnalyticsProvider } from '../lib/analyticsProvider'
import { Panel, ToolHeader } from '../components'

export function Dashboard() {
  const [days, setDays] = useState<7 | 14 | 30>(14)
  const data = MockAnalyticsProvider.getData(days)
  const values = data.dailyVisits
  const max = Math.max(...values) + 12
  const points = values.map((value, i) => `${(i / (values.length - 1)) * 580},${170 - value / max * 150}`).join(' ')
  return <><ToolHeader title="数据看板" description="用于展示产品可能的使用情况与工具热度。以下所有数据均为演示数据。" badge="CAMPUSKIT / DEMO DATA" /><div className="demo-banner"><span>●</span><strong>演示数据</strong><p>本页数字和记录均为模拟内容，并非真实访问统计。</p></div><div className="dashboard-stats"><div><span>今日访问</span><strong>{data.overview.today}</strong><small>次 · 演示数据</small></div><div><span>累计访问</span><strong>{data.overview.total.toLocaleString()}</strong><small>次 · 演示数据</small></div><div><span>工具使用次数</span><strong>{data.overview.uses.toLocaleString()}</strong><small>次 · 演示数据</small></div><div><span>平均停留时间</span><strong>{data.overview.duration}</strong><small>演示数据</small></div></div><div className="dashboard-grid"><Panel title="访问趋势" hint="演示数据"><div className="range-tabs">{([7, 14, 30] as const).map(value => <button key={value} className={days === value ? 'active' : ''} onClick={() => setDays(value)}>{value} 天</button>)}</div><div className="chart"><div className="chart-y"><span>120</span><span>80</span><span>40</span><span>0</span></div><svg viewBox="0 0 580 180" preserveAspectRatio="none" role="img" aria-label={`${days} 天模拟访问趋势`}><defs><linearGradient id="area" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#6c5ce7" stopOpacity=".23"/><stop offset="1" stopColor="#6c5ce7" stopOpacity="0"/></linearGradient></defs><line x1="0" y1="45" x2="580" y2="45"/><line x1="0" y1="90" x2="580" y2="90"/><line x1="0" y1="135" x2="580" y2="135"/><polygon points={`0,180 ${points} 580,180`} fill="url(#area)"/><polyline points={points} fill="none" stroke="#6454df" strokeWidth="3" vectorEffect="non-scaling-stroke"/></svg></div><div className="chart-x"><span>{days} 天前</span><span>今天</span></div></Panel><Panel title="工具使用排行" hint="演示数据"><div className="bar-list">{data.toolUsage.map((tool, index) => <div key={tool.name}><span>{String(index + 1).padStart(2, '0')}</span><strong>{tool.name}</strong><div className="bar-track"><i style={{ width: `${tool.count / data.toolUsage[0].count * 100}%` }} /></div><em>{tool.count}</em></div>)}</div></Panel><Panel title="工具分类占比" hint="演示数据"><div className="donut-wrap"><div className="donut"><div><strong>4</strong><span>类工具</span></div></div><div className="legend"><div><i style={{ background: '#6655e9' }} />图片工具 <strong>44%</strong></div><div><i style={{ background: '#a598f5' }} />文档工具 <strong>29%</strong></div><div><i style={{ background: '#73b7b7' }} />PDF 工具 <strong>18%</strong></div><div><i style={{ background: '#e9b88c' }} />媒体工具 <strong>9%</strong></div></div></div></Panel><Panel title="访客所在国家 / 地区" hint="演示数据"><div className="region-list">{data.regions.map(item => <div key={item.name}><span>{item.name}</span><div><i style={{ width: `${item.percent}%` }} /></div><strong>{item.percent}%</strong></div>)}</div></Panel><Panel title="最近使用情况" hint="模拟记录"><div className="activity-list">{data.recentActivity.map(item => <div key={item.time}><span className="activity-dot"/><strong>{item.tool}</strong><time>{item.time}</time></div>)}</div></Panel></div></>
}
