import { useState } from 'react'
import { Dropzone, Field, Panel, Status, ToolHeader } from '../components'
import { defaultStyles, generateDocx, type StyleConfig } from '../lib/docx'
import { formatBytes } from '../lib/files'

const labels = ['标题 1', '标题 2', '标题 3', '正文']

export function WordPage() {
  const [file, setFile] = useState<File | null>(null)
  const [active, setActive] = useState('标题 1')
  const [configs, setConfigs] = useState<Record<string, StyleConfig>>(structuredClone(defaultStyles))
  const [state, setState] = useState<'idle' | 'busy' | 'done' | 'error'>('idle')
  const [message, setMessage] = useState('')
  const current = configs[active]
  const update = (patch: Partial<StyleConfig>) => setConfigs(value => ({ ...value, [active]: { ...value[active], ...patch } }))
  async function run() { if (!file) return; setState('busy'); setMessage('正在配置 Word 样式…'); try { await generateDocx(file, configs); setState('done'); setMessage('规范模板已生成并下载。') } catch (error) { setState('error'); setMessage(error instanceof Error ? error.message : '生成失败，请换一个 DOCX 文件重试。') } }
  return <><ToolHeader title="Word 规范模板生成器" description="保留学校提供的模板，设置标题与正文样式，下载后直接在 Word 中继续写作。" badge="CAMPUSKIT / 文档工具" /><div className="workspace-grid"><div className="workspace-main"><Panel title="1. 上传学校模板" hint="仅支持 .docx"><Dropzone accept=".docx,application/vnd.openxmlformats-officedocument.wordprocessingml.document" multiple={false} onFiles={files => { const chosen = files[0]; if (!chosen?.name.toLowerCase().endsWith('.docx')) { setState('error'); setMessage('请选择 .docx 文件，旧版 .doc 暂不支持。'); return } setFile(chosen); setState('idle'); setMessage('') }} title="拖拽 DOCX 模板，或点击选择" subtitle="封面、Logo、表格和页眉页脚会尽量保留。" />{file && <div className="selected-file"><span className="file-mark">DOCX</span><div><strong>{file.name}</strong><small>已读取文档模板 · {formatBytes(file.size)}</small></div><button className="icon-button" onClick={() => setFile(null)} aria-label="移除文件">×</button></div>}</Panel>
    <Panel title="2. 设置排版样式"><div className="style-tabs" role="tablist">{labels.map(label => <button key={label} className={active === label ? 'active' : ''} onClick={() => setActive(label)} role="tab" aria-selected={active === label}>{label}</button>)}</div><div className="form-grid"><Field label="中文字体"><select value={current.cn} onChange={e => update({ cn: e.target.value })}>{['黑体', '宋体', '微软雅黑', '仿宋', '楷体', '等线'].map(v => <option key={v}>{v}</option>)}</select></Field><Field label="英文字体"><select value={current.en} onChange={e => update({ en: e.target.value })}>{['Arial', 'Times New Roman', 'Calibri', 'Georgia'].map(v => <option key={v}>{v}</option>)}</select></Field><Field label="字号（pt）"><input type="number" min="6" max="72" value={current.size} onChange={e => update({ size: Number(e.target.value) })} /></Field><Field label="对齐"><select value={current.align} onChange={e => update({ align: e.target.value as StyleConfig['align'] })}><option value="left">左对齐</option><option value="center">居中</option><option value="right">右对齐</option><option value="both">两端对齐</option></select></Field><Field label="段前（pt）"><input type="number" min="0" value={current.before} onChange={e => update({ before: Number(e.target.value) })} /></Field><Field label="段后（pt）"><input type="number" min="0" value={current.after} onChange={e => update({ after: Number(e.target.value) })} /></Field><Field label="行距（倍）"><input type="number" min="1" max="3" step="0.1" value={current.line} onChange={e => update({ line: Number(e.target.value) })} /></Field><Field label="首行缩进（字符）"><input type="number" min="0" max="8" step="0.5" value={current.indent} onChange={e => update({ indent: Number(e.target.value) })} /></Field></div><label className="check-row"><input type="checkbox" checked={current.bold} onChange={e => update({ bold: e.target.checked })} /> 加粗</label><button className="primary-button" disabled={!file || state === 'busy'} onClick={run}>{state === 'busy' ? '生成中…' : '生成规范模板'} <span>→</span></button>{state !== 'idle' && <Status kind={state}>{message}</Status>}</Panel></div>
    <div className="workspace-side"><Panel title="样式预览" hint={active}><div className="word-preview"><div className="preview-page"><p className="preview-label">预览 · {active}</p><div style={{ fontFamily: `${current.cn}, ${current.en}, serif`, fontSize: Math.max(13, Math.min(27, current.size * 1.2)), fontWeight: current.bold ? 700 : 400, textAlign: current.align === 'both' ? 'justify' : current.align, lineHeight: current.line, textIndent: `${current.indent}em` }}>{active === '正文' ? '在这里开始撰写你的社会实践报告。规范的样式，让内容更清晰。' : `${active}：在这里输入章节名称`}</div><div className="preview-lines" /></div></div><div className="preview-properties"><span>{current.cn} / {current.en}</span><span>{current.size} pt · {current.line} 倍行距</span></div></Panel><div className="tip-card"><span>✦</span><p>生成后，在 Word 的样式栏选择「标题 1 / 2 / 3」或「正文」即可套用。复杂公式、文本框、SmartArt 等内容建议生成后检查。</p></div></div></div></>
}
